FROM php:8.2-apache

# Instalar extensiones necesarias para bases de datos (PostgreSQL / MySQL)
RUN apt-get update && apt-get install -y libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql pgsql mysqli pdo_mysql

# Copiar todo el código de tu proyecto al servidor web Apache
COPY . /var/www/html/

# Configurar el puerto dinámico requerido por Render
RUN sed -i 's/80/${PORT}/g' /etc/apache2/sites-available/000-default.conf /etc/apache2/ports.conf

EXPOSE 80